add : video call & chat function
tanonkim/WebRTC-APPLICATION-backend pull request #4
Opened 2022-03-31 08:42 UTC by tanonkim

## :: 구현 목표 
- WebRTC Video Call & Chat 구현

<br />

## :: 구현 사항 설명
- Web Socket을 활용한 메시지 수신
- channels가 Web Socket의 요청을 받은 후 라우팅 설정을 확인
- 라우팅 설정을 확인 후 대응하는 Consumer을 찾고 요청 처리
- `Redis`를 저장소로 하는 채널 레이어를 사용

<br />

## :: 기타 질문 및 특이 사항
라우팅 설정이 잘못되었는지 `room_group_name`을 설정하는데 문제가 있습니다.
<img width="632" alt="스크린샷 2022-03-31 오후 5 40 45" src="https://user-images.githubusercontent.com/60570733/161014255-4b17651b-79fe-450a-85bc-76902eaba2d1.png">

2022-03-31 10:57 UTC, jasonkang14 requested changes
고생하셨습니다. comment 확인 부탁 드립니다.

2022-03-31 10:57 UTC, jasonkang14 commented on chat/consumers.py
> +        self.room_group_name = 'Room'
python class에서 상수의 선언은  `__init__()` 이나 class 이름 아래에 선언합니다. 
[python class object](https://docs.python.org/3/tutorial/classes.html#class-objects)문서를 참고해주세요

2022-03-31 10:57 UTC, jasonkang14 commented on chat/consumers.py
> +        if(action == 'new-offer') or (action =='new-answer'):
소괄호는 필요하지 않습니다.

2022-03-31 10:57 UTC, jasonkang14 commented on chat/consumers.py
> +            receive_dict['message']['receiver_channel_name'] = self.channel_name
`self.channel_name`이 선언되지 않았는데, 정상적으로 작동하나요?

2022-03-31 10:57 UTC, jasonkang14 commented on chat/consumers.py
> +        receive_dict = json.loads(text_data)
`receive_dict`의 구조를 comment에 올려주실 수 있나요? 구조를 확인하면 조금 더 효율적으로 코드를 개선할 수 있을 것 같습니다.

2022-03-31 10:57 UTC, jasonkang14 commented on chat/consumers.py
> +        if(action == 'new-offer') or (action =='new-answer'):
성능에는 차이는 없지만, 컨벤션을 지키는 측면에서 `==` 뒤에 띄어쓰기가  있을지 없을지를 통일하면 좋겠습니다.

2022-03-31 10:57 UTC, jasonkang14 commented on chat/consumers.py
> +                    'type': 'send.sdp',
`send.sdp`가 나타내는 값은 무엇인가요?

2022-03-31 10:57 UTC, jasonkang14 commented on chat/consumers.py
> +                    'type': 'send.sdp',
`channel_layer.send()`와 `group_send()`는 어떤 차이가 있나요?

2022-03-31 10:57 UTC, jasonkang14 commented on chat/consumers.py
> +class ChatConsumer(AsyncWebsocketConsumer):
초기기능은 WebRTC인데 `ChatConsumer`는 변수명이 적합하지 않은 것 같습니다. 
특히 채팅은 지금 작성하신 것 처럼 `sdp`를 공유하지 않아도 됩니다. 
작성하시고자 하는 기능에 적합하게 클래스 이름을 수정해주세요.

2022-03-31 11:04 UTC, jasonkang14 commented
추가로 
1. 에러가 있는 경우에는 코드가 PR로 올라오면 안됩니다
2. 첨부하신 스크린샷의 에러 메시지는 chat directory 안에 urls.py가 비어있기 때문입니다. channels의 routing은 asgi.py에서 이루어집니다. 
3. 지금은 채팅이 아니라 영상 연결 기능을 구현중이니 장고 앱의 이름도 변경이 필요할 것 같습니다

2022-04-01 04:49 UTC, tanonkim commented on chat/consumers.py
> +            receive_dict['message']['receiver_channel_name'] = self.channel_name
넵! 우선은 정상적으로 작동하는 것을 확인했는데, 왜 작동하는지 조금 더 깊이 생각해봐야 할 것 같습니다.

2022-04-01 09:49 UTC, tanonkim commented on chat/consumers.py
> +        receive_dict = json.loads(text_data)
다음과 같습니다.
`{'peer': 'peer_name', 'action': 'new-offer', 'message': {'sdp': {'type': 'offer', 'sdp': ’sap’}, 'receiverchannelname': ‘receiverchannelname’}}`

2022-04-02 13:33 UTC, tanonkim commented on chat/consumers.py
> +        self.room_group_name = 'Room'
네! 확인했습니다.

2022-04-02 13:49 UTC, tanonkim commented
수정 사항 반영 및 라우팅 에러 해결하였습니다.
남겨주신 리뷰사항 확인했습니다! 감사합니다~

2022-04-04 01:21 UTC, jasonkang14 approved these changes
LGTM

2022-04-04 01:21 UTC, jasonkang14 commented on call/consumers.py
> +    async def receive(self, text_data):
여기는 왠지 프런트 작업 시작하면 수정이 필요할 것 같습니다. 
지금 당장은 작업이 어려울듯해서 merge하겠습니다. 
고생하셨습니다!

2022-04-04 01:21 UTC, merged

2022-04-04 01:22 UTC, tanonkim commented on call/consumers.py
> +    async def receive(self, text_data):
넵! 확인하였습니다. 감사합니다~