[김기현] add : deployment setting
tanonkim/WebRTC-APPLICATION-backend pull request #5
Opened 2022-04-05 05:05 UTC by tanonkim

## :: 구현 목표 
- 서버 배포 설정

<br />

## :: 구현 사항 설명
- Django와 uwsgi 서버를 연결 후 nginx를 연결해 배포

**uwsgi**
- 가상환경 경로, 장고 프로젝트 폴더 경로 분리
- 옵션을 지정해 바로 서버를 열도록 로컬에서 config.ini를 추가
- uwsgi가 백그라운드에 항상 실행되도록 uwsgi.service 추가

**nginx**
- uwsgi가 아닌 브라우저 요청을 웹서버가 받도록 nginx를 연결
- ACM에서 SSL인증서 발급 후 HTTP 요청을 HTTPS 로 받도록 처리

<br />

## :: 기타 질문 및 특이 사항
**nginx 선택이유**

apache는 프로세스를 fork하거나 쓰레드를 사용하지만, 
nginx는 CPU와 관계없이 IO들을 전부 Event Listener로 미루기 때문에 흐름이 끊기지 않고 응답이 빠른 작업이 가능합니다.

추가적으로 nginx는 apache 와 달리 동시접속자 수가 많아져도 추가적인 생성비용이 들지 않고,
메모리적인 측면에서 Nginx가 System Resource를 적게 처리한다는 장점이 해당 프로젝트와 더 잘 어울린다고 생각했습니다.

<br/>
**uwsgi 선택 이유**
uwsgi가 조금 더 하드한 서비스를 위해 디자인되었고, pure C기반이기에 퍼포먼스면에서 더 우수하다고 하여 선택했습니다.

2022-04-05 05:45 UTC, jasonkang14 commented
1. nginx와 uwsgi+django를 docker화하면 운영/배포측면에서 이점이 생길 것 같다고 생각했는데 도커화를 하는게 좋을 지 궁금합니다.!
- uwsgi + django를 도커화하면 도커 이미지만 가져와서 사용하면 되기 때문에 개발할 때 편해서 자주 사용합니다.
- docker 에 [docker volumes](https://docs.docker.com/storage/volumes/)가 있는데, 로컬의 디렉토리와 컨테이너를 연결시켜서 로컬에서 한 작업이 컨테이너에도 반영되게 처리 할 수 있습니다.
- 그렇게 되면 배포되어있는 컨테이너의 코드를 바로 수정할 수 있으니 작업에도 용이하게 됩니다. 
- nginx를 도커화하는건 개발자들 사이에 의견이 좀 갈리는데  [nginx 공식문서에 도커로 배포하는 법](https://www.nginx.com/blog/deploying-nginx-nginx-plus-docker/)이 나와있는 걸 보면 잘못된 것은 아닌 것 같습니다. 
- 하지만 저는 Nginx를 도커화 하는 것을 좋아하지 않는데, 왜냐하면 ngnix가 처음 들어오는 Request들을 redirect하는 역할을 해주는데, nginx가 도커 컨테이너로 작동하면 도커에 문제가 있을때도 nginx가 제대로 작동하지 않을 수도 있습니다.
- 운영체제(OS) -> 웹서버(web server) -> 도커 순으로 리퀘스트가 전달 되는 것이 흐름상 맞다고 생각하는데, nginx가 도커 컨테이너라면 운영체제 -> 도커 -> 웹서버 -> 도커 순으로 request가 전달되는 느낌이라고 할까요. 
- 추가로 nginx가 도커화되면, 에러로 인해 컨테이너가 내려가면 에러로그 유실 등의 문제가 발생할 수 있어서 저는 nginx를 도커화 하는 것은 반대하는 입장인데, 혹시 nginx를 컨테이너로 사용하는 것을 옹호하는 입장도 들어보면 좋을 것 같습니다.

2. 추가적으로 도커화를 하려고 시도했고, 서버에서 git 클론 후 my_settings.py가 없어 오류가 발생했는데 해당 파일을 어떻게 관리해야 할 지 모르겠습니다..!
- git clone 후 `my_settngs.py`가 없어서 에러가 발생한 것은 해당 파일이 `.gitignore`에 포함되어 있기  때문일 것 같습니다. `my_settings.py`에 어떤 내용이 있는지는 알 수 없지만, 개인 컴퓨터에서 작업하기 위해 필요한 설정들을 보관한 파일일테니, 서버에도 같은 파일 이름으로 파이썬 파일을 생성해서 설정값들을 관리해주시면 될 것 같습니다.

2022-04-05 06:56 UTC, jasonkang14 requested changes

2022-04-05 06:56 UTC, jasonkang14 commented on .config/nginx/config.conf
> +    return 301 https://$host$request_uri;
ssl 설정이 없어서 redirect가 되지 않을 것 같은데 정상적으로 작동하나요?

2022-04-05 06:56 UTC, jasonkang14 commented on .config/uwsgi/config.ini
> +module = mysite.wsgi:application
mysite라는 모듈이 없어서 에러가 발생할 것 같습니다.

2022-04-05 06:56 UTC, jasonkang14 commented on .config/uwsgi/config.ini
> +pidfile = /tmp/config.pid
pid파일의 역할은 무엇인가요?

2022-04-05 07:48 UTC, tanonkim commented on .config/uwsgi/config.ini
> +module = mysite.wsgi:application
네! 확인하였습니다~ 
uwsgi 서버를 이용해 Django랑 연결되는거는 확인했는데, config.ini에 있는 옵션을 이용해 uwsgi 서버 연결하면 에러날 것 같습니다.

2022-04-06 05:07 UTC, tanonkim commented on .config/nginx/config.conf
> +    return 301 https://$host$request_uri;
letsencrypt로 발급하면 ssl 추가를 해야 하는데, aws certificate manager로 인증서를 발급하면 서버에서 들어오기 전에 처리해주는 것으로 이해했습니다!

2022-04-06 05:08 UTC, tanonkim commented on .config/uwsgi/config.ini
> +pidfile = /tmp/config.pid
오랫동안 실행되는 일부 프로세스들을 다른 프로세스들이 알 수 있도록 PID를 파일에 기록하는 역할을 한다고 이해했습니다.!

2022-04-06 05:11 UTC, tanonkim commented
로드밸런서 생성 후에 nginx 설정까지 완료했는데,
 https 리다이렉팅은 정상적으로 이루어지나 503 에러가 발생해서 `client_body_buffer_size 30K`로 버퍼 사이즈를 확장했습니다.

2022-04-06 05:16 UTC, jasonkang14 approved these changes
LGTM

2022-04-06 05:16 UTC, merged